services:


  postgres_bd:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=users'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  user-service:
    environment:
      SPRING_DATASOURCE_URL1: jdbc:postgresql://postgres_bd:5432/users
      SPRING_DATASOURCE_USERNAME1: postgres
      SPRING_DATASOURCE_PASSWORD1: postgres
    build:
      context: ./User-Service
      dockerfile: Dockerfile
    ports:
      - "8001:9001"
    depends_on:
      - postgres_bd
networks:
  crud-network: